# Generated by Django 3.1.7 on 2021-06-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic_profile',
            field=models.ImageField(null=True, upload_to='accounts_images/'),
        ),
    ]
